# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=b'%Y/%m/%d/%m/%s'),
        ),
    ]
