# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20161213_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to=b''),
        ),
    ]
