# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 07:53
from __future__ import unicode_literals

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20161213_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to=base.models.upload_path_handler),
        ),
    ]
