# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-17 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_image_likenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImageAffiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=100)),
                ('enable', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='image',
            old_name='likenumber',
            new_name='likeNumber',
        ),
    ]
