# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-17 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20161216_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimageaffiliation',
            old_name='user',
            new_name='username',
        ),
    ]
