# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20161216_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
